// LOCALHOST   
###
GET http://localhost:3000

###
GET http://localhost:3000/contacts

###
GET http://localhost:3000/contacts/63c04653182913362ec8f11a

###
GET http://localhost:3000/contacts/63c08e1877375e1eefcb61e5

###
GET http://localhost:3000/contacts/63c08e8877375e1eefcb61e7


# post routes
###
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Fred",
    "lastName":"Robinson",
    "email":"kr@gmail.com", 
    "favoriteColor":"gold",
    "birthday":"04/04/1980"
}

# put routes
###
PUT http://localhost:3000/contacts/63cca277a0211eb658391e5f HTTP/1.1
content-type: application/json

{
   "firstName":"Ralph",
   "lastName":"Hicks",
   "email":"ts@gmail.com",
   "favoriteColor":"silver",
   "birthday":"05/05/1980"
}



// PRODUCTION DEPLOY TO RENDER
###
# get all contacts on render
GET https://cse341node5.onrender.com/contacts

###
# Get individual contacts by id on render
GET https://cse341node5.onrender.com/contacts/63c04653182913362ec8f11a

###
GET https://cse341node5.onrender.com/contacts/63c08e1877375e1eefcb61e5

###
GET https://cse341node5.onrender.com/contacts/63c08e8877375e1eefcb61e7

###
POST https://cse341node5.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Kaitlyn",
    "lastName":"Robinson",
    "email":"kr@gmail.com", 
    "favoriteColor":"gold",
    "birthday":"04/04/1980"
}



